name: A workflow for my Hello World file
on: 
  push:
  workflow_dispatch:
  #Enables /deploy-test-westus command dispatch
  repository_dispatch:
    types: [deploy-test-westus-command]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
